[package]
org = "ballerinax"
name = "persist.redis"
version = "1.2.1"
authors = ["Ballerina"]
keywords = ["persist", "redis"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.redis"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-redis-native"
version = "1.2.1"
path = "../native/build/libs/persist.redis-native-1.2.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "1.2.0"
path = "./lib/persist-native-1.2.0.jar"
